global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: go_tracing_server
    static_configs:
      - targets: ["host.docker.internal:4000"]