-- +migrate Up
CREATE TABLE IF NOT EXISTS customers (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    identity_number VARCHAR(256) UNIQUE DEFAULT NULL,
    full_name TEXT DEFAULT NULL,
    status VARCHAR(20) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE = InnoDB;

-- +migrate Down
DROP TABLE if exists customers;

